package db;

import java.io.PrintWriter;
import java.sql.ResultSet;

public class form {
	public String base() {
		String  base_form = "<!DOCTYPE html>\n"
				+ "<html>\n"
				+ "<head>\n"
				+ "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n"
				+ "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n"
				+ "\n"
				+ "<meta charset=\"UTF-8\">\n"
				+ "<title>Insert title here</title>\n"
				+ "</head>\n"
				+ "<body>\n"
				+ "<img src=\"\">\n"
				+ "<p class=\"text-center\">동국 대학교 경주 캠퍼스 <br>스터디룸 예약 서비스</p>\n"
				+ "<!--  start of navbar -->\n"
				+ "<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n"
				+ "    <div class=\"container-fluid\">\n"
				+ "      <a class=\"navbar-brand\" href=\"#\">Navbar</a>\n"
				+ "      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarColor01\" aria-controls=\"navbarColor01\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
				+ "        <span class=\"navbar-toggler-icon\"></span>\n"
				+ "      </button>\n"
				+ "      <div class=\"collapse navbar-collapse\" id=\"navbarColor01\">\n"
				+ "        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n"
				+ "          <li class=\"nav-item\">\n"
				+ "            <a class=\"nav-link active\" aria-current=\"page\" href=\"login.jsp\">예약하기</a>\n"
				+ "          </li>\n"
				+ "        </ul>\n"
				+ "        <form class=\"d-flex\" role=\"search\">\n"
				+ "          <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n"
				+ "          <button class=\"btn btn-outline-light\" type=\"submit\">Search</button>\n"
				+ "        </form>\n"
				+ "      </div>\n"
				+ "    </div>\n"
				+ "  </nav>\n"
				+ "<!-- end of navbar -->\n";
		return base_form;
	}
	
	public String joinus() {
		String join = "<!DOCTYPE html>\n"
				+ "<html>\n"
				+ "<head>\n"
				+ "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n"
				+ "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n"
				+ "\n"
				+ "<meta charset=\"UTF-8\">\n"
				+ "<title>Insert title here</title>\n"
				+ "</head>\n"
				+ "<body>\n"
				+ "<img src=\"\">\n"
				+ "<p class=\"text-center\">동국 대학교 경주 캠퍼스 <br>스터디룸 예약 서비스</p>\n"
				+ "<!--  start of navbar -->\n"
				+ "<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n"
				+ "    <div class=\"container-fluid\">\n"
				+ "      <div class=\"collapse navbar-collapse\" id=\"navbarColor01\">\n"
				+ "        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n"
				+ "          <li class=\"nav-item\">\n"
				+ "            <a class=\"nav-link active\" aria-current=\"page\" href=\"register.jsp\">회원 가입</a>\n"
				+ "          </li>\n"
				+ "        </ul>\n"
				+ "        <form class=\"d-flex\" role=\"search\">\n"
				+ "          <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n"
				+ "          <button class=\"btn btn-outline-light\" type=\"submit\">Search</button>\n"
				+ "        </form>\n"
				+ "      </div>\n"
				+ "    </div>\n"
				+ "  </nav>\n"
				+ "<!-- end of navbar -->\n";

		return join;
	}
	public String myPage(String name, String sc_number) {
		String mypage = "<!DOCTYPE html>\n"
				+ "<html>\n"
				+ "<head>\n"
				+ "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n"
				+ "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n"
				+ "<meta charset=\"UTF-8\">\n"
				+ "<title>Insert title here</title>\n"
				+ "\n"
				+ "\n"
				+ "</head>\n"
				+ "<body>\n"
				+ "<img src=\"\">\n"
				+ "<p class=\"text-center\">동국 대학교 경주 캠퍼스 <br>스터디룸 예약 서비스</p>\n"
				+ "<!--  start of navbar -->\n"
				+ "<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n"
				+ "    <div class=\"container-fluid\">\n"
				+ "      <a class=\"navbar-brand\" href=\"#\">study room</a>\n"
				+ "      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarColor01\" aria-controls=\"navbarColor01\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
				+ "        <span class=\"navbar-toggler-icon\"></span>\n"
				+ "      </button>\n"
				+ "      <div class=\"collapse navbar-collapse\" id=\"navbarColor01\">\n"
				+ "        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n"
				+ "          <li class=\"nav-item\">\n"
				+ "            <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\n"
				+ "          </li>\n"
				+ "          <li class=\"nav-item\">\n"
				+ "          <form action = 'move' method = 'post' id = 'mv'>\n"
				+ "          <input type = 'hidden' value = "+name+" name = 'username'>\n"
				+ "          <input type = 'hidden' value = "+sc_number+" name = 'sc_num'>\n"
				+ "            <a class=\"nav-link\" onclick=\"document.getElementById('mv').submit();\">예약하기 </a>\n"
				+ "          </form>\n"
				+ "          </li>\n"
				+ "        </ul>\n"
				+ "        <form class=\"d-flex\" role=\"search\">\n"
				+ "          <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n"
				+ "          <button class=\"btn btn-outline-light\" type=\"submit\">Search</button>\n"
				+ "        </form>\n"
				+ "      </div>\n"
				+ "    </div>\n"
				+ "  </nav>\n"
				+ "<!-- end of navbar -->";
		return mypage;
	}
}
